version: '3'
services:
  eurekaserver1:
    image: eureka-img:latest
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=node1

  eurekaserver2:
    image: eureka-img:latest
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=node2


