version: "3"
services:
  eureka1:      # 默认情况下，其他服务可以使用服务名称连接到该服务。因此，对于peer2的节点，它需要连接http://peer1:8761/eureka/，因此需要配置该服务的名称是peer1。
    image: eurekaserver
    hostname: eureka-server1
    container_name: eureka-server1
    networks:
      - eureka-net
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=eureka-server1
  eureka2:
    image: eurekaserver
    container_name: eureka-server2
    hostname: eureka-server2
    networks:
      - eureka-net
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=eureka-server2
networks:
  eureka-net:
    driver: bridge



