spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/huanfion/Spring-Cloud-Config
          search-paths: respo
          username:
          password:
          skip-ssl-validation: false
    # 忽略掉一些指定名称的网络接口
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8889
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

